### ISSUE TITLE
Absturz

### ISSUE THREAD

**Issue by llluuuzzziii** [niccokunzmann/mundraub-android#278]
> 
[eu.quelltext.mundraub.error.txt](https://github.com/niccokunzmann/mundraub-android/files/3544685/eu.quelltext.mundraub.error.txt)

**Comment by llluuuzzziii** [comment]
Ich hoffe das hilft ;o)

**Comment by niccokunzmann** [comment]
Ja, danke!

```
java.lang.RuntimeException: java.lang.Throwable: A WebView method was called on thread 'Timer-0'. All WebView methods must be called on the same thread. (Expected Looper Looper (main, tid 2) {72c5fac} called on null, FYI main Looper is Looper (main, tid 2) {72c5fac})
	at android.webkit.WebView.checkThread(WebView.java:2486)
	at android.webkit.WebView.getUrl(WebView.java:1244)
	at eu.quelltext.mundraub.activities.map.MapBaseActivity.getUrl(MapBaseActivity.java:97)
	at eu.quelltext.mundraub.activities.map.TestFruitRadarActivity$2.run(TestFruitRadarActivity.java:42)
	at java.util.TimerThread.mainLoop(Timer.java:562)
	at java.util.TimerThread.run(Timer.java:512)
Caused by: java.lang.Throwable: A WebView method was called on thread 'Timer-0'. All WebView methods must be called on the same thread. (Expected Looper Looper (main, tid 2) {72c5fac} called on null, FYI main Looper is Looper (main, tid 2) {72c5fac})
	at android.webkit.WebView.checkThread(WebView.java:2481)
	... 5 more
LOGGER: java.lang.RuntimeException: java.lang.Throwable: A WebView method was called on thread 'Timer-0'. All WebView methods must be called on the same thread. (Expected Looper Looper (main, tid 2) {72c5fac} called on null, FYI main Looper is Looper (main, tid 2) {72c5fac})
	at android.webkit.WebView.checkThread(WebView.java:2486)
	at android.webkit.WebView.getUrl(WebView.java:1244)
	at eu.quelltext.mundraub.activities.map.MapBaseActivity.getUrl(MapBaseActivity.java:97)
	at eu.quelltext.mundraub.activities.map.TestFruitRadarActivity$2.run(TestFruitRadarActivity.java:42)
	at java.util.TimerThread.mainLoop(Timer.java:562)
	at java.util.TimerThread.run(Timer.java:512)
Caused by: java.lang.Throwable: A WebView method was called on thread 'Timer-0'. All WebView methods must be called on the same thread. (Expected Looper Looper (main, tid 2) {72c5fac} called on null, FYI main Looper is Looper (main, tid 2) {72c5fac})
	at android.webkit.WebView.checkThread(WebView.java:2481)
	... 5 more
DEBUG: TestFruitRadarActivity: activity life cycle: onPauseDEBUG: OfflinePlantsMapAPI: STOP: OfflinePlantsMapAPI at http://localhost:39768/
```
Das ist der Fehler von #260.

**Comment by niccokunzmann** [comment]
Ich schließe das mal. In der anderen Issue ist das jetzt referenziert.
Danke für das Bescheidsagen! Ich freue mich, dass jemand, der die App benutzt, sich meldet :)
