### ISSUE TITLE
Map does not show images on Android 9

### ISSUE THREAD

**Issue by niccokunzmann** [niccokunzmann/mundraub-android#303]
Several users of Android 9 have reported that the map does not load. I saw that it does not load the street map and does not load the satellite map. Zooming out does not help and an Internet connection was available.

Google statistics show that there are many Android 9 users. So, I wonder if it is unusable under all versions.
![image](https://user-images.githubusercontent.com/564768/65383497-be1b7400-dd16-11e9-89f9-776fb954f69a.png)

I do not have Android 9 nor an emulator, so I can not test it at the moment or repair it. Help is welcome.

How you can help:

- Send the log file sdcard/eu.quelltext.mundraub.error.txt
- use some logger to retrieve the log when the map opens or is reloaded
- [set it up](https://github.com/niccokunzmann/mundraub-android/blob/master/docs/setup.md) and start development

**Comment by alessandrotedd** [comment]
Just tested on my Android 9 smartphone and works fine. The log also reports:
I/ShowPlantsActivity: webView: "Done loading map."

**Comment by niccokunzmann** [comment]
Thanks for clarifying that it works for some systems. Now, I am willing to wait until someone comes where it fails. Also, it seems some Android 8 devices are also affected.
![image](https://user-images.githubusercontent.com/564768/65435821-687fbe00-de21-11e9-8226-ed8154357abf.png)
---
![image](https://user-images.githubusercontent.com/564768/65435844-72a1bc80-de21-11e9-8098-7bfe97ab610f.png)

I just saw, I can communicate with them directly. I will and ask them to join in the discussion.

**Comment by Kallagan93** [comment]
My error Log

INFO: LOGGER: : -------------- App started --------------DEBUG: Settings: received Context: eu.quelltext.mundraub.activities.AboutActivity@3b747f4DEBUG: Settings: Build.VERSION.RELEASE: 9DEBUG: Settings: Build.VERSION.SDK_INT: 28DEBUG: Settings: Build.MODEL: GM1913DEBUG: Settings: BuildConfig.VERSION_NAME: v1.218DEBUG: Settings: BuildConfig.DEBUG: falseDEBUG: Settings: BuildConfig.VERSION_CODE: 219DEBUG: Settings: COMMIT_HASH: f2f06419fb78a4aae7adeec7f7de84518147a39eDEBUG: Settings: Permissions.CAN_ASK_FOR_PERMISSIONS: trueDEBUG: Settings: useInsecureConnections: falseDEBUG: Settings: useAPIId: mundraubDEBUG: Settings: customNaOvoceHost: https://na-ovoce.czDEBUG: Settings: useCacheForPlants: trueDEBUG: Settings: useErrorReport: trueDEBUG: Settings: useOfflineMapAPI: falseDEBUG: Settings: debugMundraubMapAPI: falseDEBUG: Settings: vibrateWhenPlantIsInRange: falseDEBUG: Settings: useFruitRadarNotifications: falseDEBUG: Settings: radarPlantRangeMeters: 150DEBUG: Settings: maximumDisplayedMarkers: 100DEBUG: Settings: maximumZoomLevelForOfflineMap: 16DEBUG: Settings: downloadMapTilesForZoomLevelsLowerThanMaximum: trueDEBUG: Settings: userHasReadThePrivacyPolicy: trueDEBUG: Settings: offlineMapAreaBoundingBoxes: []DEBUG: Settings: showCategories: mundraubDEBUG: Settings: downloadMarkersFromAPI: na-ovoce,fruitmap,mundraubDEBUG: Settings: tilesToDownload: osmDEBUG: Settings: customNaOvoceDownloadUrls: DEBUG: Settings: askForPermission_android.permission.WRITE_EXTERNAL_STORAGE: trueDEBUG: AboutActivity: activity life cycle: onCreateDEBUG: AboutActivity: activity life cycle: onStartDEBUG: AboutActivity: activity life cycle: onResumeDEBUG: AboutActivity: activity life cycle: onPauseDEBUG: SettingsActivity: activity life cycle: onCreateDEBUG: SettingsActivity: activity life cycle: onStartDEBUG: SettingsActivity: activity life cycle: onResumeDEBUG: AboutActivity: activity life cycle: onStopjava.lang.RuntimeException: Unable to pause activity {eu.quelltext.mundraub/eu.quelltext.mundraub.activities.SettingsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.clearFocus()' on a null object reference
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4255)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4210)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4161)
	at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:7029)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.clearFocus()' on a null object reference
	at eu.quelltext.mundraub.activities.SettingsActivity.onPause(SettingsActivity.java:411)
	at android.app.Activity.performPause(Activity.java:7356)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1609)
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4245)
	... 12 more
LOGGER: java.lang.RuntimeException: Unable to pause activity {eu.quelltext.mundraub/eu.quelltext.mundraub.activities.SettingsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.clearFocus()' on a null object reference
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4255)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4210)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4161)
	at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:7029)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.clearFocus()' on a null object reference
	at eu.quelltext.mundraub.activities.SettingsActivity.onPause(SettingsActivity.java:411)
	at android.app.Activity.performPause(Activity.java:7356)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1609)
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4245)
	... 12 more

**Comment by niccokunzmann** [comment]
@Kallagan93 Thanks for reporting the error log. From what I read, this is the exception from #304. What happens if you open the map? I can not read something about that in the log file.

**Comment by Kallagan93** [comment]
@niccokunzmann I updated the error Log
After open the App I have the crash

**Comment by niccokunzmann** [comment]
@Kallagan93 Thanks. This is interesting. From this, I read that the AboutActivity (Information about the app) is the first thing which opens and then, the Settings are opened. I do not really know why that happens. I would expect something else. The Settings crash Because of #304. This is resolved in #305 and will be live from v1.227 on. What I do not understand is why the AboutActivity is the first thing which opens and why it goes to the Settings. Do you interact with the app?

**Comment by niccokunzmann** [comment]
Now, I have a Phone running lineage OS. It show the map. I still have no device to work on this.
